server:
  port: 8080

spring:
  application:
    name: gateway-service

# yml 에서 라우팅 및 필터삽입도 가능
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/products/**
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/orders/**
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin

# 유레카 클라이언트로 등록
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    key: YW55IHNlY3JldCBleGFtcGxlIHNlY3JldCBrZXkgZm9yIGp3dA==
