server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#    hikari:
#      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    feign:
      discovery:
        enabled: true

